//! NSPasteboard access stays on the daemon's single-threaded runtime. No shell
//! commands, clipboard history, or content logging. Borrowed ObjC refs never escape.
use super::{Board, MAX_TEXT};
use std::ffi::{CStr, c_char, c_void};
type Ref = *mut c_void;
#[link(name = "AppKit", kind = "framework")]
extern "C" {}
#[link(name = "objc")]
extern "C" {
    fn objc_getClass(name: *const c_char) -> Ref;
    fn sel_registerName(name: *const c_char) -> Ref;
    fn objc_msgSend();
    fn objc_autoreleasePoolPush() -> Ref;
    fn objc_autoreleasePoolPop(pool: Ref);
}
#[link(name = "CoreGraphics", kind = "framework")]
extern "C" {
    fn CGSessionCopyCurrentDictionary() -> Ref;
}
#[link(name = "CoreFoundation", kind = "framework")]
extern "C" {
    fn CFDictionaryGetValue(dict: Ref, key: Ref) -> Ref;
    fn CFGetTypeID(value: Ref) -> usize;
    fn CFBooleanGetTypeID() -> usize;
    fn CFBooleanGetValue(value: Ref) -> bool;
    fn CFRelease(value: Ref);
}
#[link(name = "Carbon", kind = "framework")]
extern "C" {
    fn IsSecureEventInputEnabled() -> bool;
}

struct Pool(Ref);
impl Pool {
    fn new() -> Self {
        Self(unsafe { objc_autoreleasePoolPush() })
    }
}
impl Drop for Pool {
    fn drop(&mut self) {
        unsafe { objc_autoreleasePoolPop(self.0) }
    }
}
unsafe fn sel(name: &CStr) -> Ref {
    sel_registerName(name.as_ptr())
}
unsafe fn object(receiver: Ref, selector: &CStr) -> Ref {
    let send: unsafe extern "C" fn(Ref, Ref) -> Ref =
        std::mem::transmute(objc_msgSend as unsafe extern "C" fn());
    send(receiver, sel(selector))
}
unsafe fn integer(receiver: Ref, selector: &CStr) -> isize {
    let send: unsafe extern "C" fn(Ref, Ref) -> isize =
        std::mem::transmute(objc_msgSend as unsafe extern "C" fn());
    send(receiver, sel(selector))
}
unsafe fn argument(receiver: Ref, selector: &CStr, arg: Ref) -> Ref {
    let send: unsafe extern "C" fn(Ref, Ref, Ref) -> Ref =
        std::mem::transmute(objc_msgSend as unsafe extern "C" fn());
    send(receiver, sel(selector), arg)
}
unsafe fn string(text: &str) -> Ref {
    let allocated = object(objc_getClass(c"NSString".as_ptr()), c"alloc");
    let send: unsafe extern "C" fn(Ref, Ref, *const u8, usize, usize) -> Ref =
        std::mem::transmute(objc_msgSend as unsafe extern "C" fn());
    let value = send(
        allocated,
        sel(c"initWithBytes:length:encoding:"),
        text.as_ptr(),
        text.len(),
        4,
    );
    object(value, c"autorelease")
}
unsafe fn utf8(value: Ref, limit: usize) -> Option<String> {
    if value.is_null() {
        return None;
    }
    let send: unsafe extern "C" fn(Ref, Ref, usize) -> usize =
        std::mem::transmute(objc_msgSend as unsafe extern "C" fn());
    let len = send(value, sel(c"lengthOfBytesUsingEncoding:"), 4);
    if len > limit {
        return None;
    }
    let bytes = object(value, c"UTF8String") as *const u8;
    if bytes.is_null() {
        return None;
    }
    std::str::from_utf8(std::slice::from_raw_parts(bytes, len))
        .ok()
        .map(str::to_owned)
}
unsafe fn pasteboard() -> Ref {
    object(
        objc_getClass(c"NSPasteboard".as_ptr()),
        c"generalPasteboard",
    )
}
unsafe fn boolean(dict: Ref, key: Ref) -> Option<bool> {
    let value = CFDictionaryGetValue(dict, key);
    if value.is_null() || CFGetTypeID(value) != CFBooleanGetTypeID() {
        None
    } else {
        Some(CFBooleanGetValue(value))
    }
}
unsafe fn contains(types: Ref, name: &str) -> bool {
    let send: unsafe extern "C" fn(Ref, Ref, Ref) -> bool =
        std::mem::transmute(objc_msgSend as unsafe extern "C" fn());
    send(types, sel(c"containsObject:"), string(name))
}
unsafe fn suppressed(pb: Ref, apps: &[String], exporting: bool) -> bool {
    let types = object(pb, c"types");
    // An unavailable type list is a refusal to export, never permission.
    if types.is_null() {
        return true;
    }
    for marker in [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
    ] {
        if contains(types, marker) {
            return true;
        }
    }
    if exporting && contains(types, "org.nspasteboard.AutoGeneratedType") {
        return true;
    }
    let source = argument(pb, c"stringForType:", string("org.nspasteboard.source"));
    if let Some(source) = utf8(source, 1024) {
        if apps.contains(&source)
            || (exporting
                && (source == "de.feschber.LanMouse.Dev" || source == "de.feschber.LanMouse"))
        {
            return true;
        }
    } else if !source.is_null() {
        return true;
    }
    let workspace = object(objc_getClass(c"NSWorkspace".as_ptr()), c"sharedWorkspace");
    let app = object(workspace, c"frontmostApplication");
    let Some(id) = utf8(object(app, c"bundleIdentifier"), 1024) else {
        return true;
    };
    apps.contains(&id)
}

pub(super) struct MacBoard;
impl Board for MacBoard {
    fn ready(&self) -> bool {
        let _pool = Pool::new();
        unsafe {
            if IsSecureEventInputEnabled() {
                return false;
            }
            let dict = CGSessionCopyCurrentDictionary();
            if dict.is_null() {
                return false;
            }
            let lock_key = string("CGSSessionScreenIsLocked");
            let unlocked = CFDictionaryGetValue(dict, lock_key).is_null()
                || boolean(dict, lock_key) == Some(false);
            // CGSession.h defines these keys with CFSTR macros; they are not
            // exported variables that can be linked from Rust.
            let ready = boolean(dict, string("kCGSSessionOnConsoleKey")) == Some(true)
                && boolean(dict, string("kCGSessionLoginDoneKey")) == Some(true)
                && unlocked;
            CFRelease(dict);
            ready
        }
    }
    fn count(&self) -> isize {
        let _pool = Pool::new();
        unsafe { integer(pasteboard(), c"changeCount") }
    }
    fn read(&self, expected: isize, apps: &[String]) -> Option<String> {
        let _pool = Pool::new();
        unsafe {
            let pb = pasteboard();
            if !self.ready()
                || integer(pb, c"changeCount") != expected
                || suppressed(pb, apps, true)
            {
                return None;
            }
            let text = utf8(
                argument(pb, c"stringForType:", string("public.utf8-plain-text")),
                MAX_TEXT,
            )?;
            // A change or focus switch during data provision cannot leak a
            // newly concealed value under an earlier permission decision.
            if integer(pb, c"changeCount") != expected
                || !self.ready()
                || suppressed(pb, apps, true)
            {
                return None;
            }
            Some(text)
        }
    }
    fn write(&self, expected: isize, text: &str, apps: &[String]) -> bool {
        let _pool = Pool::new();
        unsafe {
            let pb = pasteboard();
            if text.len() > MAX_TEXT
                || !self.ready()
                || integer(pb, c"changeCount") != expected
                || suppressed(pb, apps, false)
            {
                return false;
            }
            integer(pb, c"clearContents");
            let send: unsafe extern "C" fn(Ref, Ref, Ref, Ref) -> bool =
                std::mem::transmute(objc_msgSend as unsafe extern "C" fn());
            let ok = send(
                pb,
                sel(c"setString:forType:"),
                string(text),
                string("public.utf8-plain-text"),
            );
            if ok {
                send(
                    pb,
                    sel(c"setString:forType:"),
                    string("de.feschber.LanMouse"),
                    string("org.nspasteboard.source"),
                );
            }
            ok
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn native_sensitive_markers_and_suppressed_sources_are_rejected() {
        // Use isolated named pasteboards; never inspect or overwrite the user's
        // General pasteboard during automated tests.
        let _pool = Pool::new();
        unsafe {
            for marker in [
                "org.nspasteboard.ConcealedType",
                "org.nspasteboard.TransientType",
                "org.nspasteboard.AutoGeneratedType",
                "com.agilebits.onepassword",
            ] {
                let pb = object(
                    objc_getClass(c"NSPasteboard".as_ptr()),
                    c"pasteboardWithUniqueName",
                );
                let send: unsafe extern "C" fn(Ref, Ref, Ref, Ref) -> bool =
                    std::mem::transmute(objc_msgSend as unsafe extern "C" fn());
                assert!(send(
                    pb,
                    sel(c"setString:forType:"),
                    string("synthetic test value"),
                    string(marker)
                ));
                assert!(suppressed(pb, &[], true));
                object(pb, c"releaseGlobally");
            }
            let pb = object(
                objc_getClass(c"NSPasteboard".as_ptr()),
                c"pasteboardWithUniqueName",
            );
            let send: unsafe extern "C" fn(Ref, Ref, Ref, Ref) -> bool =
                std::mem::transmute(objc_msgSend as unsafe extern "C" fn());
            send(
                pb,
                sel(c"setString:forType:"),
                string("test.password.manager"),
                string("org.nspasteboard.source"),
            );
            assert!(suppressed(pb, &["test.password.manager".into()], true));
            assert!(suppressed(pb, &["test.password.manager".into()], false));
            object(pb, c"releaseGlobally");
        }
    }
    #[test]
    fn native_utf8_preserves_embedded_nul_and_checks_byte_limit() {
        let _pool = Pool::new();
        unsafe {
            let text = "🌍\0hello";
            let value = string(text);
            assert_eq!(utf8(value, text.len()).as_deref(), Some(text));
            assert!(utf8(value, text.len() - 1).is_none());
        }
    }
}
